ind_cities = ["San+Francisco%2C+CA","Seattle%2C+WA"]
li_cities = ["San+Francisco%2C%20+CA","Seattle%2C%20+WA"]

# ind_cities = ["New+York%2C+NY",
#                   "Los+Angeles%2C+CA",
#                   "Chicago%2C+IL",
#                   "Dallas%2C+TX",
#                   "Houston%2C+TX",
#                   "Washington%2C+DC",
#                   "Miami%2C+FL",
#                   "Philadelphia%2C+PA",
#                   "Atlanta%2C+GA",
#                   "Boston%2C+MA",
#                   "Phoenix%2C+AZ",
#                   "San+Francisco%2C+CA",
#                   "Seattle%2C+WA",
#                   "Denver%2C+CO",
#                   "Trenton%2C+NJ",
#                   "Austin%2C+TX",
#                   "Raleigh-Durham%2C+NC",
#                   "Charlotte%2C+NC",
#                   "Boulder%2C+CO",
#                   "San+Jose%2C+CA"]


# li_cities = ["New+York%2C%20+NY",
#                   "Los+Angeles%2C%20+CA",
#                   "Chicago%2C%20+IL",
#                   "Dallas%2C%20+TX",
#                   "Houston%2C%20+TX",
#                   "Washington%2C%20+DC",
#                   "Miami%2C%20+FL",
#                   "Philadelphia%2C%20+PA",
#                   "Atlanta%2C%20+GA",
#                   "Boston%2C%20+MA",
#                   "Phoenix%2C%20+AZ",
#                   "San+Francisco%2C%20+CA",
#                   "Seattle%2C%20+WA",
#                   "Denver%2C%20+CO",
#                   "Trenton%2C%20+NJ",
#                   "Austin%2C%20+TX",
#                   "Raleigh-Durham%2C%20+NC",
#                   "Charlotte%2C%20+NC",
#                   "Boulder%2C%20+CO",
#                   "San+Jose%2C%20+CA"]